ci:
  skip: [pylint]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.8"
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.11.0"
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/Pierre-Sassoulas/black-disable-checker/
    rev: v1.1.3
    hooks:
      - id: black-disable-checker
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.5.3
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
        exclude: "survey/static/|dev/templates/|survey/templates/|survey/locale/|survey/tests/"
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn",
            "-sn",
            "--rcfile=pyproject.toml",
            "--django-settings-module=settings",
            "--load-plugins=pylint_django",
            "--fail-on=I",
          ]
        exclude: "survey/migrations/"
