# Generated by Django 6.1.1 on 2026-09-27 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0014_survey_redirect_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="maximum_choices",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Only used for 'select multiple' questions. Leave empty for no limit.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Maximum number of choices",
            ),
        ),
    ]
